POST http://127.0.0.1:8000/users/login/
Content-Type: application/json

{"username":"admin","password":"12345"}

###

POST http://127.0.0.1:8000/group/group_creation/
Content-Type: application/json

Authorization: "d9c93a63858aa30af14e195bc523b066d3f796e6"
{
  "name": "Test Group",
  "contribution_amount": 1000,
  "number_of_members": 10,
  "cycle_length": 1,
  "start_date": "2026-03-28"
}


{"username":"admin","password":"12345"}


###

POST http://127.0.0.1:8000/users/register/

Content-Type: application/json

{"first_name":"John","last_name":"Doe","email":"john.doe@example.com","username":"johndoe123","account_number":"1234567890","age":25,"password":"securePassword123","confirm_password":"securePassword123"}