# Generated by Django 6.0 on 2026-03-26 23:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('contribution_amount', models.PositiveIntegerField(verbose_name=[django.core.validators.MinValueValidator(1000)])),
                ('number_of_memebers', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(10)])),
                ('cycle_length', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed')], default='Active')),
            ],
        ),
    ]
