# Generated by Django 6.0 on 2026-03-28 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_groupmodel_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmodel',
            old_name='number_of_memebers',
            new_name='number_of_members',
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='contribution_amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed')], default='Active', max_length=20),
        ),
    ]
