# Generated by Django 6.0 on 2026-03-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='payout_order',
            field=models.CharField(max_length=10),
        ),
    ]
